LMS.App/Controllers/Admin/AuthorController.cs
using AutoMapper;
using LMS.Application.Repositories.Entities;
using LMS.Application.ViewModels.VmEntities;
using LMS.SharedKernel.Entities;
using Microsoft.AspNetCore.Mvc;

namespace LMS.App.Controllers.Admin;

public class AuthorController : Controller
{
    private readonly IAuthorRepository _authorRepository;
    private readonly IMapper _mapper;

    public AuthorController(IAuthorRepository authorRepository, IMapper mapper)
    {
        _authorRepository = authorRepository;
        _mapper = mapper;
    }

    public async Task<IActionResult> Index()
    {
        var authorList = await _authorRepository.GetAllAsync();
        return View(_mapper.Map<List<VmAuthor>>(authorList));
    }

    public async Task<IActionResult> Details(long id)
    {
        var author = await _authorRepository.FirstOrDefaultAsync(id);
        return View(_mapper.Map<VmAuthor>(author));
    }

    [HttpGet]
    public async Task<IActionResult> AddEdit(long id)
    {
        return id switch
        {
            0 => View(new VmAuthor()),
            _ => View(_mapper.Map<VmAuthor>(await _authorRepository.FirstOrDefaultAsync(id)))
        };
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddEdit(long id, VmAuthor viewModel)
    {
        switch (id)
        {
            case 0:
                try
                {
                    if (ModelState.IsValid)
                    {


                        await _authorRepository.InsertAsync(_mapper.Map<Author>(viewModel));
                        TempData["SuccessMessage"] = $" Author added successfully.";
                        return RedirectToAction("Index");
                    }
                }
                catch (Exception ex)
                {
                    TempData["ErrorMessage"] = $"Error adding Author : {ex.Message}";
                }

                break;
            default:
                try
                {
                    var existing = await _authorRepository.FirstOrDefaultAsync(viewModel.Id);
                    if (ModelState.IsValid)
                    {

                        var author = _mapper.Map<Author>(viewModel);
                        await _authorRepository.UpdateAsync(existing.Id, author);

                        TempData["SuccessMessage"] = $" Author update successfully.";
                        return RedirectToAction("Index");
                    }
                }
                catch (Exception ex)
                {
                    TempData["ErrorMessage"] = $"Error updating Author : {ex.Message}";
                }
                break;
        }

        return View(new VmAuthor());
    }


    public async Task<IActionResult> Delete(long id)
    {
        if (id > 0)
        {
            await _authorRepository.DeleteAsync(id);
            TempData["SuccessMessage"] = $" Item remove successfully";
            return RedirectToAction("Index");
        }
        TempData["ErrorMessage"] = $"Error delete : Item not found";
        return RedirectToAction("Index");
    }
}

LMS.App/Controllers/Admin/BookController.cs
using AutoMapper;
using LMS.Application.Repositories.Entities;
using LMS.Application.ViewModels.VmEntities;
using LMS.SharedKernel.Entities;
using Microsoft.AspNetCore.Mvc;

namespace LMS.App.Controllers.Admin;

public class BookController : Controller
{
    private readonly IBookRepository _bookRepository;
    private readonly IAuthorRepository _authorRepository;
    private readonly IMapper _mapper;

    public BookController(IBookRepository bookRepository, IMapper mapper, IAuthorRepository authorRepository)
    {
        _bookRepository = bookRepository;
        _mapper = mapper;
        _authorRepository = authorRepository;
    }


    public async Task<IActionResult> Index()
    {
        var authorList = await _bookRepository.GetAllAsync(x => x.Author);
        return View(_mapper.Map<List<VmBook>>(authorList));
    }

    public async Task<IActionResult> Details(long id)
    {
        var author = await _bookRepository.FirstOrDefaultAsync(id, x => x.Author);
        return View(_mapper.Map<VmBook>(author));
    }

    [HttpGet]
    public async Task<IActionResult> AddEdit(long id)
    {
        ViewData["AuthorId"] = await _authorRepository.GetDropdownAsync();
        return id switch
        {
            0 => View(new VmBook()),
            _ => View(_mapper.Map<VmBook>(await _bookRepository.FirstOrDefaultAsync(id)))
        };
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddEdit(long id, VmBook viewModel)
    {
        switch (id)
        {
            case 0:
                try
                {
                    if (ModelState.IsValid)
                    {


                        await _bookRepository.InsertAsync(_mapper.Map<Book>(viewModel));
                        TempData["SuccessMessage"] = $" Book added successfully.";
                        return RedirectToAction("Index");
                    }
                }
                catch (Exception ex)
                {
                    TempData["ErrorMessage"] = $"Error adding Book : {ex.Message}";
                }

                break;
            default:
                try
                {
                    var existing = await _bookRepository.FirstOrDefaultAsync(viewModel.Id);
                    if (ModelState.IsValid)
                    {

                        var author = _mapper.Map<Book>(viewModel);
                        await _bookRepository.UpdateAsync(existing.Id, author);

                        TempData["SuccessMessage"] = $" Book update successfully.";
                        return RedirectToAction("Index");
                    }
                }
                catch (Exception ex)
                {
                    TempData["ErrorMessage"] = $"Error updating Book : {ex.Message}";
                }
                break;
        }
        ViewData["AuthorId"] = await _authorRepository.GetDropdownAsync();
        return View(new VmBook());
    }


    public async Task<IActionResult> Delete(long id)
    {
        if (id > 0)
        {
            await _bookRepository.DeleteAsync(id);
            TempData["SuccessMessage"] = $" Item remove successfully";
            return RedirectToAction("Index");
        }
        TempData["ErrorMessage"] = $"Error delete : Item not found";
        return RedirectToAction("Index");
    }
}

LMS.App/Controllers/Admin/DashboardController.cs
using LMS.Application.Repositories.Entities;
using LMS.Application.ViewModels.VmEntities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LMS.App.Controllers.Admin;

public class DashboardController : Controller
{
    private readonly IBookRepository _bookRepository;
    private readonly IMemberRepository _memberRepository;
    private readonly IBorrowdBookRepository _borrowdBookRepository;
    private readonly IAuthorRepository _authorRepository;

    public DashboardController(IBookRepository bookRepository, IMemberRepository memberRepository, IBorrowdBookRepository borrowdBookRepository, IAuthorRepository authorRepository)
    {
        _bookRepository = bookRepository;
        _memberRepository = memberRepository;
        _borrowdBookRepository = borrowdBookRepository;
        _authorRepository = authorRepository;
    }

    public async Task<IActionResult> Index()
    {
        var dashboard = new VmDashboard
        {
            TotalAuthor = await _authorRepository.GetAll().CountAsync(),
            TotalBook = await _bookRepository.GetAll().CountAsync(),
            TotalMember = await _memberRepository.GetAll().CountAsync(),
            TotalBookIssue = await _borrowdBookRepository.TotalBorrowBook(),
        };
        return View(dashboard);
    }
}

LMS.App/Controllers/Admin/MemberController.cs
using AutoMapper;
using LMS.Application.Repositories.Entities;
using LMS.Application.ViewModels.VmEntities;
using LMS.SharedKernel.Entities;
using Microsoft.AspNetCore.Mvc;

namespace LMS.App.Controllers.Admin;

public class MemberController : Controller
{
    private readonly IMemberRepository _memberRepository;
    private readonly IMapper _mapper;

    public MemberController(IMemberRepository memberRepository, IMapper mapper)
    {
        _memberRepository = memberRepository;
        _mapper = mapper;
    }

    public async Task<IActionResult> Index()
    {
        var memberList = await _memberRepository.GetAllAsync();
        return View(_mapper.Map<List<VmMember>>(memberList));
    }

    public async Task<IActionResult> Details(long id)
    {
        var author = await _memberRepository.FirstOrDefaultAsync(id);
        return View(_mapper.Map<VmMember>(author));
    }

    [HttpGet]
    public async Task<IActionResult> AddEdit(long id)
    {
        return id switch
        {
            0 => View(new VmMember()),
            _ => View(_mapper.Map<VmMember>(await _memberRepository.FirstOrDefaultAsync(id)))
        };
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddEdit(long id, VmMember viewModel)
    {
        switch (id)
        {
            case 0:
                try
                {
                    if (ModelState.IsValid)
                    {


                        await _memberRepository.InsertAsync(_mapper.Map<Member>(viewModel));
                        TempData["SuccessMessage"] = $" Member added successfully.";
                        return RedirectToAction("Index");
                    }
                }
                catch (Exception ex)
                {
                    TempData["ErrorMessage"] = $"Error adding Member : {ex.Message}";
                }

                break;
            default:
                try
                {
                    var existing = await _memberRepository.FirstOrDefaultAsync(viewModel.Id);
                    if (ModelState.IsValid)
                    {

                        var author = _mapper.Map<Member>(viewModel);
                        await _memberRepository.UpdateAsync(existing.Id, author);

                        TempData["SuccessMessage"] = $" Member update successfully.";
                        return RedirectToAction("Index");
                    }
                }
                catch (Exception ex)
                {
                    TempData["ErrorMessage"] = $"Error updating Member : {ex.Message}";
                }
                break;
        }
        return View(new VmMember());
    }


    public async Task<IActionResult> Delete(long id)
    {
        if (id > 0)
        {
            await _memberRepository.DeleteAsync(id);
            TempData["SuccessMessage"] = $" Item remove successfully";
            return RedirectToAction("Index");
        }
        TempData["ErrorMessage"] = $"Error delete : Item not found";
        return RedirectToAction("Index");
    }
}

LMS.App/Views/Shared/Backend/_AdminlteFooter.cshtml
<footer class="main-footer d-flex justify-content-between pb-0">
    <div>
        <strong>Copyright &copy; @DateTime.Now.Year <a asp-action="Index" asp-controller="Dashboard">Library Management System</a>.</strong>
        <b>Version</b> 1.0.0
    </div>
    <p>Developed by: <a class="text-capitalize" href="https://github.com/khpolash" target="_blank"> Kamrul Hasan </a></p>
</footer>

LMS.App/Views/Shared/Backend/_AdminlteMainHeader.cshtml
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>

    <ul class="navbar-nav ml-auto align-items-center">
        @await Html.PartialAsync("Backend/_LoginPartial")
        <li class="nav-item">
            <a class="nav-link" data-bs-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
    </ul>
</nav>

LMS.App/Views/Shared/Backend/_AdminlteMainSidebar.cshtml
<aside class="main-sidebar sidebar-light-info elevation-1">
    <a asp-action="Index" asp-controller="Dashboard" class="brand-link">
        <img src="~/images/lms.png" alt="LMS" width="30" height="30" class="img-circle elevation-0" style="opacity: .8">
        <span class="brand-text font-weight-light">Library Management</span>
    </a>
    <!-- Sidebar -->
    <div class="sidebar">
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Dashboard" class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Dashboard" && ViewContext.RouteData.Values["Action"].ToString() == "Index" ? "active" : "")">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Author" class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Author" && ViewContext.RouteData.Values["Action"].ToString() == "Index" ? "active" : "")">
                        <i class="nav-icon fas fa-user"></i>
                        <p>Author</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Book" class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Book" && ViewContext.RouteData.Values["Action"].ToString() == "Index" ? "active" : "")">
                        <i class="nav-icon fa-solid fa-book"></i>
                        <p>Book</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Member" class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Member" && ViewContext.RouteData.Values["Action"].ToString() == "Index" ? "active" : "")">
                        <i class="nav-icon fas fa-users"></i>
                        <p>Member</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="BorrowdBook" class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "BorrowdBook" && ViewContext.RouteData.Values["Action"].ToString() == "Index" ? "active" : "")">
                        <i class="nav-icon fa-solid fa-receipt"></i>
                        <p>Borrowd Book</p>
                    </a>
                </li>                
            </ul>
        </nav>
    </div>
</aside>

LMS.App/Views/Shared/Backend/_AdminlteScripts.cshtml
<script src="~/lib/jquery/jquery.min.js"></script>
<script src="~/lib/jqueryui/jquery-ui.min.js"></script>
<script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/lib/overlayscrollbars/js/OverlayScrollbars.min.js"></script>
<script src="~/lib/admin-lte/js/adminlte.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/select2/js/select2.min.js"></script>
<script src="~/lib/sweetalert2/sweetalert2.all.min.js"></script>
<script src="~/lib/font-awesome/js/all.min.js"></script>
<script src="~/lib/datatables.net/dataTables.min.js"></script>
<script src="~/lib/datatables.net-bs5/dataTables.bootstrap5.min.js"></script>
<script src="~/lib/datatables-responsive/dataTables.responsive.min.js"></script>
<script src="~/lib/datatables.net-responsive-bs5/responsive.bootstrap5.min.js"></script>

<script>
    $('#dataTable').DataTable({
        pageLength: 5,
        lengthMenu: [[5, 10, 20, 50, 100], [5, 10, 20, 50, 100]],
        responsive: true,
        select: {
            selector: 'td:not(:first-child)',
            style: 'os'
        }
    });

</script>
<script>
    $.widget.bridge('uibutton', $.ui.button)
    $(function () {
        var currentRoute = window.location.href;
        var currentRouteSplit = currentRoute.split("/");
        //console.log(currentRouteSplit)

        // for single sidebar menu
        $('ul.nav-sidebar a').filter(function () {
            var allRoute = this.href;
            var allRouteSplit = this.href.split('/')
            if (currentRouteSplit.length > 3) {
                return currentRouteSplit[3] == allRouteSplit[3]
            }
            return currentRoute == allRoute;
        }).addClass('active');

        // for sidebar menu and treeview
        $('ul.nav-treeview a').filter(function () {
            var allRoute = this.href;
            var allRouteSplit = this.href.split('/')
            if (currentRouteSplit.length > 3) {
                return currentRouteSplit[3] == allRouteSplit[3]
            }
        }).parentsUntil(".nav-sidebar > .nav-treeview")
            .css({ 'display': 'block' })
            .addClass('menu-open').prev('a')
            .addClass('active');
    });
</script>
<script>
    function confirmAndDelete(element) {
        var itemId = element.getAttribute("asp-route-id");
        var confirmationMessage = 'Are you sure you want to delete item ?';

        Swal.fire({
            title: 'Confirmation',
            text: confirmationMessage,
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#d33',
            cancelButtonColor: '#3085d6',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                deleteItem(element);
            }
        });

        return false;
    }
    function deleteItem(element) {
        var deleteUrl = element.getAttribute("href");
        window.location.href = deleteUrl;
    }
</script>
<script>
    var toastMixin = Swal.mixin({
        toast: true,
        icon: 'success',
        title: 'General Title',
        animation: true,
        position: 'top-right',
        showConfirmButton: false,
        timer: 3000,
        timerProgressBar: true,
        didOpen: (toast) => {
            toast.addEventListener('mouseenter', Swal.stopTimer)
            toast.addEventListener('mouseleave', Swal.resumeTimer)
        }
    });
</script>
@if (TempData["SuccessMessage"] != null)
{
    <script>
        toastMixin.fire({
            title: '@TempData["SuccessMessage"]'
        });
    </script>
}
<script src="~/js/site.js"></script>

LMS.App/Views/Shared/Backend/_AdminlteStyles.cshtml
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">


<link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/lib/admin-lte/css/adminlte.min.css" rel="stylesheet" />

<link href="~/lib/overlayscrollbars/css/OverlayScrollbars.min.css" rel="stylesheet" />
<link href="~/lib/sweetalert2/sweetalert2.min.css" rel="stylesheet" />
<link href="~/lib/datatables.net-bs5/dataTables.bootstrap5.min.css" rel="stylesheet" />
<link href="~/lib/datatables.net-responsive-bs5/responsive.bootstrap5.min.css" rel="stylesheet" />