LMS.App/Controllers/Admin/BookController.cs
using AutoMapper;
using LMS.Application.Repositories.Entities;
using LMS.Application.ViewModels.VmEntities;
using LMS.SharedKernel.Entities;
using Microsoft.AspNetCore.Mvc;

namespace LMS.App.Controllers.Admin;

public class BookController : Controller
{
    private readonly IBookRepository _bookRepository;
    private readonly IAuthorRepository _authorRepository;
    private readonly IMapper _mapper;

    public BookController(IBookRepository bookRepository, IMapper mapper, IAuthorRepository authorRepository)
    {
        _bookRepository = bookRepository;
        _mapper = mapper;
        _authorRepository = authorRepository;
    }


    public async Task<IActionResult> Index()
    {
        var authorList = await _bookRepository.GetAllAsync(x => x.Author);
        return View(_mapper.Map<List<VmBook>>(authorList));
    }

    public async Task<IActionResult> Details(long id)
    {
        var author = await _bookRepository.FirstOrDefaultAsync(id, x => x.Author);
        return View(_mapper.Map<VmBook>(author));
    }

    [HttpGet]
    public async Task<IActionResult> AddEdit(long id)
    {
        ViewData["AuthorId"] = await _authorRepository.GetDropdownAsync();
        return id switch
        {
            0 => View(new VmBook()),
            _ => View(_mapper.Map<VmBook>(await _bookRepository.FirstOrDefaultAsync(id)))
        };
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddEdit(long id, VmBook viewModel)
    {
        switch (id)
        {
            case 0:
                try
                {
                    if (ModelState.IsValid)
                    {


                        await _bookRepository.InsertAsync(_mapper.Map<Book>(viewModel));
                        TempData["SuccessMessage"] = $" Book added successfully.";
                        return RedirectToAction("Index");
                    }
                }
                catch (Exception ex)
                {
                    TempData["ErrorMessage"] = $"Error adding Book : {ex.Message}";
                }

                break;
            default:
                try
                {
                    var existing = await _bookRepository.FirstOrDefaultAsync(viewModel.Id);
                    if (ModelState.IsValid)
                    {

                        var author = _mapper.Map<Book>(viewModel);
                        await _bookRepository.UpdateAsync(existing.Id, author);

                        TempData["SuccessMessage"] = $" Book update successfully.";
                        return RedirectToAction("Index");
                    }
                }
                catch (Exception ex)
                {
                    TempData["ErrorMessage"] = $"Error updating Book : {ex.Message}";
                }
                break;
        }
        ViewData["AuthorId"] = await _authorRepository.GetDropdownAsync();
        return View(new VmBook());
    }


    public async Task<IActionResult> Delete(long id)
    {
        if (id > 0)
        {
            await _bookRepository.DeleteAsync(id);
            TempData["SuccessMessage"] = $" Item remove successfully";
            return RedirectToAction("Index");
        }
        TempData["ErrorMessage"] = $"Error delete : Item not found";
        return RedirectToAction("Index");
    }
}

LMS.App/Controllers/Admin/BorrowdBookController.cs
using AutoMapper;
using LMS.Application.Repositories.Entities;
using LMS.Application.ViewModels.VmEntities;
using LMS.SharedKernel.Entities;
using LMS.SharedKernel.Core;
using Microsoft.AspNetCore.Mvc;

namespace LMS.App.Controllers.Admin;

public class BorrowdBookController : Controller
{
    private readonly IBorrowdBookRepository _borrowdBookRepository;
    private readonly IBookRepository _bookRepository;
    private readonly IMemberRepository _memberRepository;
    private readonly IMapper _mapper;

    public BorrowdBookController(IBorrowdBookRepository borrowdBookRepository, IMapper mapper, IBookRepository bookRepository, IMemberRepository memberRepository)
    {
        _borrowdBookRepository = borrowdBookRepository;
        _mapper = mapper;
        _bookRepository = bookRepository;
        _memberRepository = memberRepository;
    }

    public async Task<IActionResult> Index()
    {
        var memberList = await _borrowdBookRepository.GetAllAsync(x => x.Book, x => x.Member);
        return View(_mapper.Map<List<VmBorrowdBook>>(memberList));
    }

    public async Task<IActionResult> Details(long id)
    {
        var author = await _borrowdBookRepository.FirstOrDefaultAsync(id, x => x.Book, x => x.Member);
        return View(_mapper.Map<VmBorrowdBook>(author));
    }

    [HttpGet]
    public async Task<IActionResult> AddEdit(long id)
    {
        ViewData["BookId"] = await _bookRepository.GetDropdownAsync();
        ViewData["MemberId"] = await _memberRepository.GetDropdownAsync();
        return id switch
        {
            0 => View(new VmBorrowdBook()),
            _ => View(_mapper.Map<VmBorrowdBook>(await _borrowdBookRepository.FirstOrDefaultAsync(id)))
        };
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddEdit(long id, VmBorrowdBook viewModel)
    {
        switch (id)
        {
            case 0:
                try
                {
                    if (ModelState.IsValid)
                    {
                        await _borrowdBookRepository.InsertAsync(_mapper.Map<BorrowdBook>(viewModel));
                        await _bookRepository.DecrementAvailableCopies(viewModel.BookId);
                        TempData["SuccessMessage"] = $" BorrowdBook added successfully.";
                        return RedirectToAction("Index");
                    }
                }
                catch (Exception ex)
                {
                    TempData["ErrorMessage"] = $"Error adding BorrowdBook : {ex.Message}";
                }

                break;
            default:
                try
                {
                    var existing = await _borrowdBookRepository.FirstOrDefaultAsync(viewModel.Id);
                    if (ModelState.IsValid)
                    {

                        var author = _mapper.Map<BorrowdBook>(viewModel);
                        await _borrowdBookRepository.UpdateAsync(existing.Id, author);

                        TempData["SuccessMessage"] = $" BorrowdBook update successfully.";
                        return RedirectToAction("Index");
                    }
                }
                catch (Exception ex)
                {
                    TempData["ErrorMessage"] = $"Error updating BorrowdBook : {ex.Message}";
                }
                break;
        }
        ViewData["BookId"] = await _bookRepository.GetDropdownAsync();
        ViewData["MemberId"] = await _memberRepository.GetDropdownAsync();
        return View(new VmBorrowdBook());
    }


    public async Task<ActionResult> ReturnBook(long id)
    {
        if (id > 0)
        {
            var borrowBook = await _borrowdBookRepository.FirstOrDefaultAsync(id);
            borrowBook.Status = BookStatus.Returned;
            await _borrowdBookRepository.UpdateAsync(id, borrowBook);
            await _bookRepository.IncrementAvailableCopies(borrowBook.BookId);
            TempData["SuccessMessage"] = $" Item return successfully";
            return RedirectToAction(nameof(Index));
        }
        TempData["ErrorMessage"] = $"Error return : return has some issue";
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Delete(long id)
    {
        if (id > 0)
        {
            await _borrowdBookRepository.DeleteAsync(id);
            TempData["SuccessMessage"] = $" Item remove successfully";
            return RedirectToAction("Index");
        }
        TempData["ErrorMessage"] = $"Error delete : Item not found";
        return RedirectToAction("Index");
    }
}

LMS.App/Controllers/Admin/DashboardController.cs
using LMS.Application.Repositories.Entities;
using LMS.Application.ViewModels.VmEntities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LMS.App.Controllers.Admin;

public class DashboardController : Controller
{
    private readonly IBookRepository _bookRepository;
    private readonly IMemberRepository _memberRepository;
    private readonly IBorrowdBookRepository _borrowdBookRepository;
    private readonly IAuthorRepository _authorRepository;

    public DashboardController(IBookRepository bookRepository, IMemberRepository memberRepository, IBorrowdBookRepository borrowdBookRepository, IAuthorRepository authorRepository)
    {
        _bookRepository = bookRepository;
        _memberRepository = memberRepository;
        _borrowdBookRepository = borrowdBookRepository;
        _authorRepository = authorRepository;
    }

    public async Task<IActionResult> Index()
    {
        var dashboard = new VmDashboard
        {
            TotalAuthor = await _authorRepository.GetAll().CountAsync(),
            TotalBook = await _bookRepository.GetAll().CountAsync(),
            TotalMember = await _memberRepository.GetAll().CountAsync(),
            TotalBookIssue = await _borrowdBookRepository.TotalBorrowBook(),
        };
        return View(dashboard);
    }
}

LMS.App/Views/BorrowdBook/AddEdit.cshtml
@model LMS.Application.ViewModels.VmEntities.VmBorrowdBook
@{
    ViewData["Title"] = "AddEdit";
    Layout = "~/Views/Shared/_Adminlte.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Issue Book </h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a asp-controller="Dashboard" asp-action="Index">Home</a></li>
                    <li class="breadcrumb-item active">Issue Book</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<section class="content ">
    <div class="card w-4 ">
        <div class="card-header">
            <h3 class="card-title">Issue Book</h3>
            <div class="card-body">
                <form asp-action="AddEdit" asp-controller="BorrowdBook" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input asp-for="Id" type="hidden" />
                    <div class="modal-body form-horizontal">
                        <div class="row">

                            <div class="col-md-6">
                                <label asp-for="BookId" class="col-form-label"></label>
                                <select asp-for="BookId" asp-items="@(ViewBag.BookId)" class="form-control select2">
                                    <option value="">--Select Book--</option>
                                </select>
                                <span asp-validation-for="MemberId" class="text-danger"></span>
                            </div>

                            <div class="col-md-6">
                                <label asp-for="MemberId" class="col-form-label"></label>
                                <select asp-for="MemberId" asp-items="@(ViewBag.MemberId)" class="form-control select2">
                                    <option value="">--Select Member--</option>
                                </select>
                                <span asp-validation-for="MemberId" class="text-danger"></span>
                            </div>

                            <div class="col-md-6">
                                <label asp-for="BorrowDate" class=" col-form-label"></label>
                                <input asp-for="BorrowDate" class="form-control" value="@DateTimeOffset.UtcNow.ToString("yyyy-MM-dd")" />
                                <span asp-validation-for="BorrowDate" class="text-danger"></span>
                            </div>

                            <div class="col-md-6">
                                <label asp-for="ReturnDate" class=" col-form-label"></label>
                                <input asp-for="ReturnDate" class="form-control" value="@DateTimeOffset.UtcNow.AddDays(7).ToString("yyyy-MM-dd")"/>
                                <span asp-validation-for="ReturnDate" class="text-danger"></span>
                            </div>

                            <div class="col-md-6">
                                <label asp-for="Status" class=" col-form-label"></label>
                                <select asp-for="Status" class="form-control" asp-items="@Html.GetEnumSelectList<LMS.SharedKernel.Core.BookStatus>()">
                                    <option>Status</option>
                                </select>
                                <span asp-validation-for="Status" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group mt-2">
                            <button type="submit" class="btn btn-sm btn-info"><i class="bi bi-save"></i> Issue Book</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

LMS.App/Views/BorrowdBook/Details.cshtml
@model LMS.Application.ViewModels.VmEntities.VmBorrowdBook

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Adminlte.cshtml";
}


<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Book</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a asp-controller="Dashboard" asp-action="Index">Home</a></li>
                    <li class="breadcrumb-item active">Book</li>
                </ol>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Book List</h3>
            <div class="card-tools">
                <a asp-action="AddEdit" asp-controller="Book" class="btn btn-info btn-sm">
                    <i class="fa-regular fa-square-plus"></i> Add</a>
                <a asp-action="AddEdit" asp-controller="Book" asp-route-id="@Model.Id" class="btn btn-info btn-sm">
                    <i class="fa-regular fa-pen-to-square"></i> Edit</a>
                <a asp-action="Index" asp-controller="Book" class="btn btn-info btn-sm">
                    <i class="fa-solid fa-list"></i> List</a>
            </div>
        </div>
        <div class="card-body">
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Id)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Id)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.BookTitle)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.MemberName)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.BorrowDate)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.BorrowDate)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.ReturnDate)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.ReturnDate)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Status)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Status)
                </dd>

            </dl>
        </div>
    </div>

</section>

LMS.App/Views/BorrowdBook/Index.cshtml
@model IEnumerable<LMS.Application.ViewModels.VmEntities.VmBorrowdBook>
@using LMS.SharedKernel.Core
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Adminlte.cshtml";
    var counter = 1;
    DateTime currentDate = DateTime.Now.Date;
}


<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Borrowd Book</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a asp-controller="Dashboard" asp-action="Index">Home</a></li>
                    <li class="breadcrumb-item active">Issue Book</li>
                </ol>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Borrowd Book List</h3>
            <div class="card-tools">
                <a asp-action="AddEdit" asp-controller="BorrowdBook" class="btn btn-info btn-sm">
                    <i class="fa-regular fa-square-plus"></i> Issue Book
                </a>
            </div>
        </div>
        <div class="card-body">
            <table class="table nowrap" id="dataTable">
                <thead class="nowrap">
                    <tr>
                        <th>#</th>
                        <th>
                            @Html.DisplayNameFor(model => model.MemberName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.BookTitle)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.BorrowDate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ReturnDate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Status)
                        </th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr class="@(item.Status!= BookStatus.Returned && item.ReturnDate < currentDate ? "table-danger" : "")">
                            <td>@counter</td>
                            <td>
                                @Html.DisplayFor(modelItem => item.MemberName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.BookTitle)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.BorrowDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ReturnDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Status)
                            </td>
                            <td style="vertical-align: middle; width:140px;">
                                <a href="@Url.Action("ReturnBook", new { id = item.Id })" class="btn btn-link btn-sm text-success @(item.Status==LMS.SharedKernel.Core.BookStatus.Returned ? "disabled" : "")" title="Return">
                                    <i class="fa-solid fa-arrow-rotate-left"></i> Return
                                </a>
                                |
                                <a href="@Url.Action("Details", new { id = item.Id })" class="btn btn-link btn-sm text-primary" title="Details">
                                    <i class="far fa-eye"></i>
                                </a>
                                @*|
                                <a href="@Url.Action("Delete", new { id = item.Id })" class="btn btn-link btn-sm text-danger" title="Delete" onclick="return confirmAndDelete(this);">
                                    <i class="fas fa-trash-alt"></i>
                                </a>*@
                            </td>
                        </tr>
                        counter++;
                    }
                </tbody>
            </table>
        </div>
    </div>

</section>